[package]
name = "wen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3"
anyhow = "1"

hickory-resolver ={ version = "0.24", features = ["dns-over-native-tls"]}
